### ISSUE TITLE
What is this code? Is it being used?

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/dnschain#126]
@WeMeetAgain See: https://github.com/okTurtles/dnschain/blob/mocha/src/lib/dns.coffee#L262-L267

The [coverage report](https://okturtles.com/other/coverage.html#src/lib/dns.coffee) indicates it was never called. Is this old code that needs to be removed because it's no longer being used anymore?

**Comment by WeMeetAgain** [comment]
Oh, yeah, it should be removed
