### ISSUE TITLE
Post remaining bounties on some issue?

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/dnschain#130]
We've got $120 left in BountySource that we can put on something.

I'm thinking maybe one of:

- #109 Debian package (#110 depends on this)
- #51 PFSense package
- #10 Add stats via redis or memcached (this requires first merging `admin` branch tho)
- #14 Add sendmail-type support for reporting critical errors

cc @SGrondin @WeMeetAgain 

Anyone else feel free to chime in!

**Comment by Napoleon** [comment]
+1 pfsense #51

**Comment by tofutim** [comment]
oh yeah, another vote for pfsense #51

**Comment by tofutim** [comment]
I think for this to be successful, inclusion in mass produced hardware will be very helpful. Is it hard to make a pfsense package?

**Comment by tofutim** [comment]
Ignorant question: does dnschain work in FreeBSD?

**Comment by taoeffect** [comment]
> Finally, would one use PowerDNS? Something from pfsense? Does dnschain by itself work as a DNS source?

You can use DNSChain as a traditional DNS server, but I personally don't recommend it (yet). I think PowerDNS' recursor has been tuned to do that job efficiently and well. More work needs to be done on [native-dns](https://github.com/tjfontaine/node-dns) for it to be at parity with PowerDNS. The two work great together though.

**Comment by taoeffect** [comment]
As far as Namecoin on FreeBSD goes, you can always try compiling namecoind from source.

**Comment by taoeffect** [comment]
After some considered thought, it's become clear to me that Issue #101 — **Switch to getdns-node instead of native-dns** is of highest priority, so the $120 bounty is going on that, and I strongly encourage other users of DNSChain to donate bounties to that issue as well.

Reason being: native-dns is not a very good DNS library, and it seems to be somewhat abandoned right now. I do not have the time to work on improving it. With a switch to getdns, DNSChain should work great as a standalone DNS server for traditional DNS and we wouldn't need to recommend PowerDNS alongside it.
