### ISSUE TITLE
Nxt resolver not working

### ISSUE THREAD

**Issue by slothbag** [okTurtles/dnschain#138]
Just trying out the latest release to test Nxt resolving.  I have put in my Nxt connect and port details, it looks like it is querying the API just fine, but I cant get a valid response from any of the aliases.

I've tried test1.nxt, test4.nxt, toenu.nxt, domain1.nxt and domain2.nxt

I get the error "err: 'Cannot read property \'ns\' of undefined'"

**Comment by taoeffect** [comment]
@toenu23, could you see if maybe you can help him out?

**Comment by taoeffect** [comment]
This should be fixed in 0.5.2, just released.

**Comment by taoeffect** [comment]
@slothbag please let us know if you'd like us to add your server to the list of public servers.
