### ISSUE TITLE
Fingerprint demo URL responds with "unsupported resource" 

### ISSUE THREAD

**Issue by rippler** [okTurtles/dnschain#146]
https://github.com/okTurtles/dnschain/blob/master/docs/How-do-I-use-it.md - there's a link that's supposed to show server fingerprint, but server responds with "unsupported resource" 

Link: http://api.dnschain.net/v1/namecoin/fingerprint

**Comment by WeMeetAgain** [comment]
Try [https://api.dnschain.net/v1/~~namecoin~~dnschain/fingerprint](https://api.dnschain.net/v1/dnschain/fingerprint)

The idea is that the fingerprint is a dnschain-specific resource, rather than a namecoin resource.
