### ISSUE TITLE
Unsupported datastore: none

### ISSUE THREAD

**Issue by tofutim** [okTurtles/dnschain#149]
My last step in a dnschain/powerdns install in Ubuntu, I try `curl http://127.0.0.1:8000/d/okturtles` but I get
```
Unsupported datastore: none
```
Looking up d/okturtles.bit and everything else does work.

Looking up d/okturtles.bit and everything else does work. I see that it comes from
```
            if not (datastore = @dnschain.chains[datastoreName])
	                return @sendErr req, res, 400, "Unsupported datastore: #{datastoreName}"
```
And maybe related to the warnings at startup:
```
[INFO] Loading DNSChain config from: /home/tim/.dnschain.conf
2015-04-03T22:11:42.835Z - warn: [Global] Couldn't find keyid configuration: 
{ '0': '/home/tim/.KeyID/config.json',
  '1': '/home/tim/Library/Application Support/KeyID/config.json' }
2015-04-03T22:11:43.013Z - info: [Global] namecoin configuration path: /home/tim/.namecoin/namecoin.conf
2015-04-03T22:11:43.409Z - info: [NXT] Disabled. Missing params: 
{ '0': 'nxt:port',
  '1': 'nxt:connect' }
2015-04-03T22:11:43.875Z - info: [ICANN] Server started.
2015-04-03T22:11:43.878Z - info: [NMC] rpc to namecoind on: 127.0.0.1:8336
2015-04-03T22:11:43.879Z - info: [NMC] Server started.
2015-04-03T22:11:43.885Z - info: [Redis] cache not enabled
2015-04-03T22:11:43.885Z - info: [Redis] Server started.
2015-04-03T22:11:43.939Z - info: [DNS] started DNS 
```

**Comment by taoeffect** [comment]
So, that is the old API.

If you want to use DNSChain like that, you need to pass in a `Host` header of `namecoin.dns` along with your request.

We recommend you use [the new API](https://github.com/okTurtles/dnschain/blob/master/docs/What-is-it.md#API) instead.

Closing. Can re-open if that didn't address your question.

**Comment by tofutim** [comment]
That certainly does the trick. Need to update the sample documentation (for Debian). Will send pull request (which will include instructions for Ubuntu).

**Comment by tofutim** [comment]
Incidentally, the new nomenclature, to be a bit juvenile, introduces a bad interaction between %2F and okturtles in the example. I miss the old one.

**Comment by taoeffect** [comment]
> introduces a bad interaction between %2F and okturtles in the example.

It's necessary to support the API, otherwise there's no way to distinguish keys from actions and properties.

> I miss the old one.

The old one is still supported. You can just put nginx in front of DNSChain and have it force the Host header to be `namecoin.dns`. That's what we do on our server and it works just like it used to:

[http://dns.dnschain.net/id/greg](http://dns.dnschain.net/id/greg)

**Comment by tofutim** [comment]
When you specify the Host does it mean that the api will no longer work?

**Comment by taoeffect** [comment]
> When you specify the Host does it mean that the api will no longer work?

Both APIs will work.

**Comment by tofutim** [comment]
Indeed they do. Thanks!
