### ISSUE TITLE
Startup launch in FreeBSD

### ISSUE THREAD

**Issue by tofutim** [okTurtles/dnschain#152]
When I install PowerDNS Recursor in FreeBSD using `pkg install powerdns-recursor`, I see the following:
```
 *******************************************************************
 If you want to use the powerdns recursor,
 you need the following line in /etc/rc.conf(.local)

    pdns_recursor_enable="YES"

 Configuration templates are available in /usr/local/etc/pdns
 as recursor.conf-dist.
*******************************************************************
```
So I make the change in rc.conf and recursor.conf and `shutdown -r now` and magically recursor is alive and well. How can I make this happen with `namecoind` and `dnschain`? Incidentally, when manually started with `namecoind &` and `dnschain &`, the whole system does work on FreeBSD. Any tips from FreeBSD gurus much appreciated.

I guess what I'm asking is *do you haz teh codez*?

**Comment by tofutim** [comment]
I'm close to a solution on this, just need to figure out how to get the FreeBSD init to point to the right conf file.

**Comment by taoeffect** [comment]
Well, I am not a FreeBSD expert, and this question seems more appropriate for [the forums](https://forums.okturtles.com/), but as far as that last warning goes, it suggests you either haven't installed coffee-script, or you did but it's not in your $PATH.

**Comment by tofutim** [comment]
This is resolved in the instructions
