### ISSUE TITLE
wrong url for demo

### ISSUE THREAD

**Issue by rezad1393** [okTurtles/dnschain#165]
in https://github.com/okTurtles/dnschain/blob/master/docs/How-do-I-use-it.md document the url for 
"Query: What is the IP address of okturtles.bit?

    https://api.dnschain.net/v1/namecoin/key/d%2Fokturtles"

goes to "https://api.dnschain.net/v1/namecoin/key/id%2Fgreg"

**Comment by taoeffect** [comment]
Thanks for pointing this out! There's a PR with this fix (and other documentation fixes) that's almost ready to be merged from @dotmacro.
