### ISSUE TITLE
Domain used in documentation examples ( okturtles.bit ) returns NXDOMAIN

### ISSUE THREAD

**Issue by sorano** [okTurtles/dnschain#176]
Greetings dear dnschain developers & users.

I just noticed that okturtles.bit now returns NXDOMAIN, this could be confusing for new dnschain users since that domain is used in the documentation examples:

https://github.com/okTurtles/dnschain/blob/dev/docs/How-do-I-run-my-own.md
https://github.com/okTurtles/dnschain/blob/master/docs/setting-up-dnschain-namecoin-powerdns-server.md

Querying my own install:
dig -p 5333 @127.0.0.1 okturtles.bit

; <<>> DiG 9.9.5-9+deb8u6-Debian <<>> -p 5333 @127.0.0.1 okturtles.bit
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: **NXDOMAIN**, id: 52040
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;okturtles.bit.			IN	A

;; Query time: 15 msec
;; SERVER: 127.0.0.1#5333(127.0.0.1)
;; WHEN: Wed Mar 30 11:15:08 CEST 2016
;; MSG SIZE  rcvd: 31

Querying a public server

dig @192.184.93.146 okturtles.bit

; <<>> DiG 9.9.5-9+deb8u6-Debian <<>> @192.184.93.146 okturtles.bit
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: **NXDOMAIN**, id: 35826
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;okturtles.bit.			IN	A

;; Query time: 189 msec
;; SERVER: 192.184.93.146#53(192.184.93.146)
;; WHEN: Wed Mar 30 11:19:49 CEST 2016
;; MSG SIZE  rcvd: 31

**Comment by ysangkok** [comment]
You still mention okturtles.bit on that page even though example.bit is used...
