### ISSUE TITLE
can't reach .bit domains

### ISSUE THREAD

**Issue by negatratoron** [okTurtles/dnschain#181]
I've set `192.184.93.146` and `54.85.5.167` as my DNS servers, and I can reach normal sites like google, but I cannot reach .bit sites like `http://isup.bit/`.  Having never been able to reach .bit sites, I'm not sure if the ones I'm trying are down, or if my setup is wrong.  What are some .bit sites that you can reach?

**Comment by taoeffect** [comment]
For various reasons (mostly resource / time constrains) we are not running a Namecoin node on `192.184.93.146`. If you'd like to access .bit domains, I recommend setting up your own DNSChain + namecoin combo.

**Comment by subnetsRU** [comment]
You can reach http://nf.bit or http://asterisk.bit as examples.

Also you can use forward zone to my DNS servers for .bit: http://bitname.ru/index.php?sci=8
Also you can try to use OpenNIC DNS servers, they are resolv .bit: https://www.opennic.org/
Also you can try to use browser exten: https://blockchain-dns.info
