### ISSUE TITLE
Prevent DNS Amplification attacks [$90]

### ISSUE THREAD

**Issue by SGrondin** [okTurtles/dnschain#35]
The DNSChain code right now is not production ready as it can be used for DDOS attacks by the thousands of automated scripts on the internet hunting for badly configured DNS Servers.

DNS lookups need to be throttled on a IP+Domain basis.

**Comment by SGrondin** [comment]
Any update on this?

**Comment by taoeffect** [comment]
@SGrondin Sorry, vacation took hold, then some fires needed to be put out.

I think this may be a good opportunity for me to add a bloody decent testing framework to DNSChain. There's no really good / proper way to see whether what you did works without one (other than writing some crappy ad-hock scripts, but why would you do that when that is essentially what a testing framework does already..?).

So, I'm currently looking into closing this issue by closing #12 (Add testing suite), and then testing this properly.

**Comment by taoeffect** [comment]
I've verified via the `modular` branch (see 0c808bd) that DNS throttling works. I didn't make any tests for HTTP(S) but I figure that probably works too (and if not, easy to fix since bottleneck stuff is working in principle). Closing and will give bounty to @SGrondin.

Fantastic work!
