### ISSUE TITLE
JSON API specs

### ISSUE THREAD

**Issue by dschuermann** [okTurtles/dnschain#45]
I'd like to know the JSON specification if there is any. A JSON API to search for users based on their full name would also be nice.

**Comment by taoeffect** [comment]
@dschuermann We've completely rewritten those specs, please have a look again:

https://github.com/openname/openname-specifications/blob/master/resolvers.md

Here's an example:

```
https://api.example.com/v1/namecoin/key/id%2Fbob
https://api.example.com/v1/bitcoin/addr/MywyjpyBbFTsHkevcoYnSaifShG2Et8R3S
https://api.example.com/v1/namecoin/key/id%2Fclinton/transfer?to_addr=ea3df...
http://api.example.com/v1/resolver/fingerprint
```

URL structure:

    /{version}/{chain|resolver}/{resource}/{property}/{operation}{resp_format}?{args}

Prelim support coming in 0.5.

Thoughts?

**Comment by dschuermann** [comment]
Hey @taoeffect 
we are currently overloaded with other efforts, but I linked it to our issue.
Thanks for working on this!

**Comment by taoeffect** [comment]
No problem! Closing this for now then, feel free to re-open or create another issue if you need it!
